name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or 'main' if you're using 'main' as the default branch
  pull_request:
    branches:
      - master  # or 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner environment (Ubuntu in this case)

    permissions:
      contents: write    # Allow write access to repository contents
      pages: write       # Allow write access to GitHub Pages
      id-token: write    # Allow the GitHub Actions bot to generate an ID token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config user.name "FkyingAbhishek"
        git config user.email "i.abhishekkumarchoudhary.online@gmail.com"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: npm test -- --coverage --passWithNoTests

    - name: Build the app
      run: npm run build

    # Create gh-pages branch and commit changes
    - name: Create gh-pages branch and commit changes
      run: |
        git checkout --orphan gh-pages   # Create a new orphan branch
        git rm -rf .                     # Remove all files (not affecting master branch)
        cp -r build/* .                  # Copy the build files to the root
        git add .                        # Add all new files
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages  # Force push to the gh-pages branch

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
